### ISSUE TITLE
Update featured image and text

### ISSUE THREAD

**Issue by MirandaEcho** [INN/inn#117]
Text: 
NewsMatch 2019: Join the largest grassroots fundraising campaign supporting nonprofit news

Link:
newsmatch.org

Image:
![Borderzine_UTEP News Match-1 - Dino Chiecchi](https://user-images.githubusercontent.com/48263361/68053151-3fbcd500-fcb9-11e9-90f3-beef50b9528b.jpg)

**Comment by benlk** [comment]
This is deployed to inn.org. :shipit:

**Comment by benlk** [comment]
Time to switch to a new image.

**Comment by benlk** [comment]
- [x] new image downloaded from https://inn.photoshelter.com/gallery-image/2018-NewsMatch-National-Photo-Day/G0000HNDoy1AiYKc/I0000w_IShywkPAk at full resolution
- [ ] ImageMagick command for generating asset sizes
- [ ] srcset in the template
- [ ] image credit, if possible?

**Comment by benlk** [comment]
Deployed as of this evening.
