### ISSUE TITLE
Updates to Blog Section

### ISSUE THREAD

**Issue by kaylima** [INN/inn#23]
1. Go to the homepage mockup/wireframe for inn.org.
2. Look at the "ANNOUNCEMENTS" section.

RESULT: Title of section = "ANNOUNCEMENTS".
EXPECT: Change "ANNOUNCEMENTS" to "BLOG".

RESULT: The 2nd and 3rd blog posts seem like they're details of the first post, and not easily distinguishable as additional posts.
EXPECT: Update the visual hierarchy for the "BLOG" section of the homepage.

**Comment by julia67** [comment]
@kaylima I’m curious what the reason is for this change? “Blog” sounds dated and v. casual to me.

**Comment by kaylima** [comment]
RESULT: titles of posts are different sizes (top one is bigger)
EXPECT: 
- make them all the same size
- maybe only have 3 total
- maybe remove the lines between
