### ISSUE TITLE
QA Review - Mobile

### ISSUE THREAD

**Issue by kaylima** [INN/inn#43]
## Homepage

iPhone 6/5:
- [x] All content under the main header needs to be centered vertically
- [ ] Newsletter signup: email address input and subscribe box need to resize to fit on one line
- [x] Newsletter signup: force everything after "INNovation!" to the 2nd line
- [ ] Logo in footer can be smaller
- [x] Navigation: there's 2 donate nav items, remove one

**Comment by benlk** [comment]
> Navigation: there's 2 donate nav items, remove one

This was a configuration change on staging; I don't recall what change was made, though. Having the "donate" button in the main nav and not in the Global Nav fixes the problem.


> All content under the main header needs to be centered vertically

Which main header?

>  Newsletter signup: email address input and subscribe box need to resize to fit on one line

If we do this, the box becomes too short to show someone's entire email address.

>  Logo in footer can be smaller

How much smaller, compared to the current size?


![inndev staging wpengine com- iphone 6 1](https://user-images.githubusercontent.com/1754187/28582203-931a31ee-7132-11e7-96ab-e1bce802663b.png)

**Comment by benlk** [comment]
I think we covered all this during discussion, so I'm closing this issue. If we need to make changes, let's put those in new issues.
