### ISSUE TITLE
News Match alert update

### ISSUE THREAD

**Issue by julia67** [INN/inn#51]
## **Use whatever the actual messaging is supposed to be**

Let's get it to look like this:

<img width="1518" alt="screen shot 2017-09-29 at 4 28 43 pm" src="https://user-images.githubusercontent.com/1643734/31036804-75bae10e-a533-11e7-9a00-3071f44ac7de.png">

Here's the HTML (the inline styles are just for clarity, should be added to stylesheet like normal):
```
<div class="alert" style="border-bottom:10px solid #33BF95; background-color:#fff;">
	<p>
		<a href="https://www.newsmatch.org/">
			<img src="https://giving-day-content.givegab.com/inn2017/app/images/day-of-giving-logo-horizontal.svg" alt="News Match: Quality journalism matters." width="220" style="margin:.75em 0 15px 0;">
		</a>
		<strong>
			<a href="https://www.newsmatch.org/" style="color:#33BF95;">Donate now and double your impact. </a>
		</strong>
	</p>
</div>
```

On mobile the image should switch to a block element and center, and the padding on the alert box should increase:

<img width="396" alt="screen shot 2017-09-29 at 4 40 35 pm" src="https://user-images.githubusercontent.com/1643734/31037140-114ab3c8-a535-11e7-8229-38ec89e15519.png">

```
.alert img {
    display: block;
    margin: .75em auto 0 auto;
}
.alert {
    padding: 1em 2.5%;
}
```

**Comment by benlk** [comment]
Should we remove the emerging leaders header at this time?

**Comment by julia67** [comment]
No, there's been no direction on what would replace it. So just update the alert.

**Comment by julia67** [comment]
Staging looks pretty good – please update the padding on the alert box to:

```
.alert {
    padding: 1em 0 .75em 0;
}
```
